version: '3'

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mydatabasepassword
      POSTGRES_DB: kvs

  kvs:
    build: kvs
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: kvs
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mydatabasepassword
    ports:
      - "8080:8080"
    depends_on:
      - postgres
